### ISSUE TITLE
[Feature]: Have the default for new emails be the webdomain @ chosenDomain.com

### ISSUE THREAD

**Issue by jlhjlh** [Curetix/mailflare-extension#13]
### Feature Description

I prefer to organize my emails by the domain, service, or company for which I'm creating the email. For instance, if I'm signing up for a new account at Outback.com, I'll set up my email alias as outback@myDomain.com. It would be incredibly useful if the plug-in could automatically fill in this part for me, similar to this example:

<img width="382" alt="image" src="https://github.com/Curetix/mailflare-extension/assets/10662400/3a9a6d1a-9e30-4bcc-8546-24060027cd05">

It does store the domain name in the description field, but that isn't visible in the default alias view on Cloudflare.com:

![image](https://github.com/Curetix/mailflare-extension/assets/10662400/9f413ef3-f348-4033-aebb-ac9d1f99e43e)

This lack of visibility means a random 5-character email address doesn't provide any useful context in that view. Moreover, I suspect that spam filters might view an email address composed of random characters with more suspicion, potentially affecting its spam score and, by extension, its deliverability.

Given that the script likely has access to the URL, it should be feasible to extract the domain name minus extension and automatically populate the "Custom alias" field with it. An extension might be OK too but I'm wary of "." (dots) in email addresses.

Cheers.

### Solution idea

While I'm not familiar with JavaScript, I'm willing to try and work it out if needed.

**Comment by Curetix** [comment]
Yeah, this is definitely possible. In fact, there is already the option to use the current domain as a prefix for the random character/word format alias, but those have a minimum length so you can't have just the domain atm. I'll think about the best way to do this.

**Comment by Curetix** [comment]
Alright, sorry it took so long, been pretty busy. I've decided to add a new alias format called `Domain`:

![image](https://github.com/Curetix/mailflare-extension/assets/15160542/37d5c9a2-10a4-47dd-bb69-e4a08aa8914a)

I'll test the changes a bit more and will release an update asap.
