### ISSUE TITLE
v1.1.1 breaks CSS on Gmail and Facebook

### ISSUE THREAD

**Issue by klaki892** [Curetix/mailflare-extension#2]
Running Google Chrome version 119.0.6045.160 & Windows 10

When enabling the latest version of Mailflare I'm witnessing the following oddities:

On Gmail's website, checkboxes for selecting mail are going away.
Before: 
![image](https://github.com/Curetix/mailflare-extension/assets/17878901/abfa69d0-f147-4855-a016-7992ba69d027)

After (Extension enabled):
![image](https://github.com/Curetix/mailflare-extension/assets/17878901/7772c5d1-c26e-4076-a850-280ff76b4bf5)

Text is shifted (padding missing?) and the checkboxes completely disappear. 

On Facebook, pop up messengers have had their header bars shortened:

Before:
![image](https://github.com/Curetix/mailflare-extension/assets/17878901/fb67bd42-a7c6-4f6e-9969-9dab2e96c4fe)

After: 
![image](https://github.com/Curetix/mailflare-extension/assets/17878901/f8b6cc12-0e87-4056-aa48-8fb681d26fc0)

Notice that the profile picture buttons are breaking the edges in the after picture but have padding in the before picture.

here are the settings im currently running with:
![image](https://github.com/Curetix/mailflare-extension/assets/17878901/e7c405b2-f24a-4da0-a016-4469c9d3bed2)

This issue also occurs when it's the only enabled extension while in an incognito window. 

_______
No errors are currently being surfaced from the extension's service worker when reloading the pages however the following error occurs when turning off the extension (likely not related)

error log paste here: https://pastecode.io/s/za69a7xv

_____
Reverting to Mailflare version 1.0.3 resolves these display issues.

**Comment by Curetix** [comment]
Thanks for reporting this, I just pushed v1.1.2 which should fix the issue. The content script for the quick-create button will not inject styles in the page anymore. Let me know if you find any sites that still have issues. (Chrome store release will take a while, the previous version is still pending)
