### ISSUE TITLE
[Bug]: Authentication Error

### ISSUE THREAD

**Issue by unalkalkan** [Curetix/mailflare-extension#20]
### What is this bug about?

When I get a token with the config specified in the README.md, I get the following error in browser extension:

![image](https://github.com/Curetix/mailflare-extension/assets/9661442/f677e572-0a03-4c76-8c2d-09d1d063caa2)

Here's the token config:

![image](https://github.com/Curetix/mailflare-extension/assets/9661442/ca4abda0-9c26-4e39-b036-0091d6d955b6)

So I dug in a little bit and sent the /email/routing/rules request with curl with the API Token, and I got this:

```bash
$ curl --request GET \
  --url https://api.cloudflare.com/client/v4/zones/$ZONE_ID/email/routing/rules \
  --header 'Content-Type: application/json' \
  --header 'Authorization: Bearer $API_TOKEN'

{"success":false,"errors":[{"code":10000,"message":"Authentication error"}]}
```

I created a new token with Read access to all resources and Edit access to Email Routing Rules, then I was able to successfully sent the request.

So either I am missing something with the first config, or it needs an additional resource that is not added into the README.md

I'll dig in more when I got time, I'll be removing some resource read accesses to narrow it down to what else is actually needed.

**Comment by Curetix** [comment]
Looks like you're missing the `Zone | Email Routing Rules | Edit` permission in the first token.

**Comment by unalkalkan** [comment]
Ooops, that should be it. It flew over my head I guess haha.
Thanks for the quick reply!
